AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - test/spec/generated_spec_test.rb
    - test/excludes/**/*

Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
